username: <username>
password: <password>
command: <command>
root_directory: <root_directory>
notification:
   active: <true/false>
   server: <server ip-address, or name>
   from_host: <from email address>
   to_host:
      - <to email address>
   subject: 
      normal: <normal subject>
      error:  <subject in error case>
   template: <path to template.j2>
zones: 
   <zone_name>:
     active: <true/false>
     devices: 
       - name: <device_name>
         ip: <device_ip>
         sleep: <sleep_time>
         terminal: <terminal command>
         active: <true/false>
